### ISSUE TITLE
Little Error In Plugin UltimateJailBreak_New.sma

### ISSUE THREAD

**Issue by akshayspawn** [tonykaram1993/UltimateJailBreak#1]
In /\* Clcmd */ Section in the plugin you have registered clcmd commands two time.

![error](https://cloud.githubusercontent.com/assets/11715728/6978443/93dc6aec-d9f0-11e4-95de-faa237c69642.PNG)

**Comment by tonykaram1993** [comment]
say and say_team are not the same commands.

I am confused, what do you mean?
